apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30011
  type: NodePort
