apiVersion: v1
kind: Service
metadata:
  name: eurekaServer-service
spec:
  selector:
    app: eurekaServer
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30061
  type: NodePort
