apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  strategy:
    rollingUpdate: 
      maxSurge: 50% 
      maxUnavailable: 10%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: qiuer0121/eurekaserver:latest
        ports:
        - containerPort: 8761

