apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaServer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaServer
  template:
    metadata:
      labels:
        app: eurekaServer
    spec:
      containers:
      - name: eurekaServer
        image: qiuer0121/eurekaServer:latest
        ports:
        - containerPort: 8761

