apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaServer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eurekaServer
  strategy:
    rollingUpdate: 
      maxSurge: 50% 
      maxUnavailable: 10%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: eurekaServer
    spec:
      containers:
      - name: eurekaServer
        image: qiuer0121/eurekaServer:latest
        ports:
        - containerPort: 8761
        resources: 
          limits: 
            cpu: 800m 
            memory: 5Gi 
          requests:  
            cpu: 50m
            memory: 100Mi

