apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  strategy:
    rollingUpdate: 
      maxSurge: 50% 
      maxUnavailable: 10%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: bxr0820/eurekaserver:latest
        ports:
        - containerPort: 8761
        resources:
          requests:
            cpu: "50m"  # 请求的 CPU 资源
          limits:
            cpu: "1000m"  # CPU 使用的最大限制

